### ISSUE TITLE
Checklist for next schema updates 

### ISSUE THREAD

**Issue by UlrikeS91** [HumanBrainProject/openMINDS_SANDS#86]
- [x] remove folder structure within "v0.1" (#83) 

- [x] rename "v0.1" to "v1.0" (decided during meeting) 

- [x] add `title` to each schema as was suggested and implemented for all openMINDS schemas (e.g. https://github.com/HumanBrainProject/openMINDS/pull/128) **--> not `title` but `_label`**

- [x] add `minItem` to all `"type": "array"` as was pointed out in https://github.com/HumanBrainProject/openMINDS/pull/90

- [x] add `uniqueItem` (suggestions) where useful, also related to https://github.com/HumanBrainProject/openMINDS/pull/90

- [x] delete `definitions.json` because new linking way #90 makes it redundant

- [x] replace `$ref` as proposed in #90 **--> totally different, see https://github.com/HumanBrainProject/openMINDS/issues/131**

- [x] merge `visualizationParameters.schema.json` properties into `annotation.schema.json` and remove the schema #84 + remove `protocol` from property `criteria` (decided to only point to `protocolExecution`) #57 

- [x] check use of `definedIn` and expected objects (`fileInstance` vs. `image`) and check if `visualizedIn` would be alternative when `image` is the expected object (raised during meeting) **--> make changes as suggested below**

- [x] update some of the property descriptions to make them consistent and clearer (started by Heidi and Ulrike) **--> different because no more descriptions but `instructions`**

- [x] update `anatomicalEntity` and `entityToEntity` according to #30

**Comment by xgui3783** [comment]
when the v1.0 become finalised, can we tag a release? This is so that rather than referencing master branch? This would make generated JSON less brittle.

**Comment by UlrikeS91** [comment]
> when the v1.0 become finalised, can we tag a release? This is so that rather than referencing master branch? This would make generated JSON less brittle.

Thanks, @xgui3783! Based on our meeting earlier today (@lzehl), this is already the plan :) Feel free to give some valuable tips on how to do this best, because I have never made a release on GitHub :D

**Comment by lzehl** [comment]
@UlrikeS91 for the title: see comment in https://github.com/HumanBrainProject/openMINDS/issues/128

**Comment by UlrikeS91** [comment]
> @UlrikeS91 for the title: see comment in [HumanBrainProject/openMINDS#128](https://github.com/HumanBrainProject/openMINDS/pull/128)

Thanks!

**Comment by apdavison** [comment]
I would be cautious about releasing v1.0 until the schemas have seen some use, i.e. there should first be at least a successful dry-run of the migration

**Comment by UlrikeS91** [comment]
To the `definedIn` checkpoint: I looked thorugh all SANDS schemas and these are the times we give a property that expects either `fileInstance` or `image`:

`fileInstance`:
- `atlasTerminology` --> `definedIn`
- `electrodeContact` --> `definedIn`
- `electrodeContact` --> `relatedRecordings`
- `electrodeContact` --> `relatedStimulations`
- `image` --> `definedIn`

`image`:
- `annotation` --> `definedIn` (still in `visualizationParameters`, but will be moved to `annotation`)
- `annotation` --> `inspiredBy`
- `coordinateSpace` --> `defaultImage`

The idea is to use `definedIn` solely for when a `fileInstance` is expected. So, it was suggested to change `annotation` --> `definedIn` --> `image` to `annotation` --> **`visualizedIn`** --> `image`. Additionally, we could add `visualizedIn` as a property to `electrodeContact`. Then, `definedIn` points to the file with e.g. the coordinates and `visualizedIn` points to an image that shows e.g. the coordinate annotated in a brain slice. 

Any objections to this, @aeidi89, @skoehnen, @lzehl and @blixilla?

**Comment by UlrikeS91** [comment]
Fixed and merged with #94
